"""
Composer: Structural Integrator for Cognitive Substrate

This module implements the Composer role as defined in cognitive_substrate.json.
It reads the full Phase-1 corpus, extracts theoretical primitives, and generates
a unified cognitive artifact that preserves all invariants.

The Composer does NOT:
- Invent new theory beyond provided corpus
- Optimize beyond stated author intentions
- Simplify by omitting documented constraints

The Composer DOES:
- Map all provided works into single internal representation
- Compose artifact that preserves every invariant
- Resolve conflicts only by referencing original author intent
"""

import argparse
import json
from typing import Dict, Any, List, Optional, Set
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class TheoreticalPrimitive:
    """A fundamental concept extracted from the corpus"""
    name: str
    source_file: str
    source_space: str  # 'constraint', 'ethical', or 'perceptual'
    definition: str
    constraints: List[str] = field(default_factory=list)
    dependencies: Set[str] = field(default_factory=set)
    citations: List[str] = field(default_factory=list)


@dataclass
class CognitiveArtifact:
    """The unified structure generated by Composer"""
    primitives: Dict[str, TheoreticalPrimitive]
    integration_map: Dict[str, List[str]]  # How primitives connect
    invariants: List[str]  # Preserved constraints
    source_citations: Dict[str, str]  # Traceability to original corpus


class CognitiveSubstrateComposer:
    """
    Composer: Structural Integrator
    
    Role: Map all provided works into single internal representation
    Input: All papers, notes, implementations from Phase-1 corpus
    Output: Unified structure respecting all three theoretical spaces
    """
    
    def __init__(
        self,
        constitution_path: str,
        corpus_root: Optional[str] = None,
        explicit_space_roots: Optional[Dict[str, str]] = None
    ):
        """
        Initialize Composer with Constitution and corpus location.
        
        Args:
            constitution_path: Path to cognitive_substrate.json
            corpus_root: Optional root directory containing sibling source repositories
            explicit_space_roots: Optional explicit per-space source roots
        """
        # Load Constitution
        with open(constitution_path, 'r', encoding='utf-8') as f:
            self.constitution = json.load(f)['cognitive_substrate']
        
        self.repo_root = Path(constitution_path).resolve().parent
        self.corpus_root = Path(corpus_root).resolve() if corpus_root else None
        self.primitives: Dict[str, TheoreticalPrimitive] = {}
        self.conflicts: List[str] = []
        self.explicit_space_roots = {
            key: Path(value).resolve()
            for key, value in (explicit_space_roots or {}).items()
        }
        self.corpus_paths = self._resolve_corpus_paths()

    def _resolve_corpus_paths(self) -> Dict[str, Path]:
        """Resolve source directories for each theoretical space."""
        search_roots = [self.repo_root.parent]
        if self.corpus_root:
            search_roots.insert(0, self.corpus_root)

        candidates = {
            'constraint': ['nature_1.8_law', 'phase14', 'project-manuals'],
            'ethical': ['cognitive-lab', 'post-alignment-lab'],
            'perceptual': ['aesthetic-resonator']
        }

        resolved: Dict[str, Path] = {}
        missing: List[str] = []

        for space, repo_names in candidates.items():
            explicit = self.explicit_space_roots.get(space)
            if explicit:
                resolved[space] = explicit
                continue

            match = None
            for root in search_roots:
                for repo_name in repo_names:
                    candidate = root / repo_name
                    if candidate.exists():
                        match = candidate
                        break
                if match:
                    break

            if match:
                resolved[space] = match
            else:
                missing.append(space)

        if missing:
            raise FileNotFoundError(
                "Composer requires accessible corpus repositories for "
                f"{', '.join(missing)}. Provide --corpus-root or explicit "
                "--*-root arguments so composition does not run against an empty corpus."
            )

        return resolved
    
    def load_corpus(self) -> None:
        """
        Load and parse all documents from Phase-1 corpus.
        Extracts theoretical primitives from each space.
        """
        print("[Composer] Loading Phase-1 corpus...")
        
        # Load constraint space (1.8 Law)
        self._load_space('constraint', [
            'docs/K_1.8_THEORETICAL_JUSTIFICATION.md'
        ])
        
        # Load ethical space (Post-Alignment AI)
        self._load_space('ethical', [
            'post_alignment_paper_draft.md',
            'post_alignment_conclusion.md',
            'post_alignment_phase2.py'
        ])
        
        # Load perceptual space (Aesthetic Resonator)
        self._load_space('perceptual', [
            'docs/pulse_research_abstract.md',
            'docs/K_1.8_THEORETICAL_JUSTIFICATION.md'
        ])
        
        if not self.primitives:
            raise RuntimeError("Composer loaded zero theoretical primitives; refusing to emit an empty artifact.")

        print(f"[Composer] Loaded {len(self.primitives)} theoretical primitives")
    
    def _load_space(self, space: str, files: List[str]) -> None:
        """Load documents from a specific theoretical space"""
        base_path = self.corpus_paths[space]
        
        for file_rel in files:
            file_path = base_path / file_rel
            if not file_path.exists():
                raise FileNotFoundError(
                    f"Required corpus file is missing for {space}: {file_path}"
                )
            
            print(f"[Composer] Parsing {space}/{file_rel}...")
            self._extract_primitives(file_path, space)
    
    def _extract_primitives(self, file_path: Path, space: str) -> None:
        """
        Extract theoretical primitives from a document.
        
        This is a simplified extraction - in production, this would use
        more sophisticated NLP or structured parsing.
        """
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Extract key concepts based on space
        if space == 'constraint':
            self._extract_constraint_primitives(content, str(file_path))
        elif space == 'ethical':
            self._extract_ethical_primitives(content, str(file_path))
        elif space == 'perceptual':
            self._extract_perceptual_primitives(content, str(file_path))
    
    def _extract_constraint_primitives(self, content: str, source: str) -> None:
        """Extract primitives from 1.8 Law documents"""
        # K=1.8 threshold
        if 'K=1.8' in content or 'k_threshold' in content:
            self.primitives['k_threshold'] = TheoreticalPrimitive(
                name='k_threshold',
                source_file=source,
                source_space='constraint',
                definition='Information-theoretic boundary at log₂(3.5) ≈ 1.8',
                constraints=['H > 1.8 → LEAP mode', 'H ≤ 1.8 → AVE mode'],
                citations=['Shannon Information Theory', 'Zipf\'s Law']
            )
        
        # Entropy modes
        if 'LEAP' in content and 'AVE' in content:
            self.primitives['entropy_modes'] = TheoreticalPrimitive(
                name='entropy_modes',
                source_file=source,
                source_space='constraint',
                definition='Mode switching based on entropy threshold',
                constraints=['LEAP: exploration when H > 1.8', 'AVE: exploitation when H ≤ 1.8'],
                dependencies={'k_threshold'}
            )
        
        # Irreversibility
        if 'irreversib' in content.lower():
            self.primitives['irreversibility_budget'] = TheoreticalPrimitive(
                name='irreversibility_budget',
                source_file=source,
                source_space='constraint',
                definition='Maximum allowable non-reversible operations',
                constraints=['Operations crossing irreversibility boundaries require K-value justification']
            )
    
    def _extract_ethical_primitives(self, content: str, source: str) -> None:
        """Extract primitives from Post-Alignment AI documents"""
        # Commitment window
        if 'commitment' in content.lower() and ('k=' in content or 'window' in content.lower()):
            self.primitives['commitment_window'] = TheoreticalPrimitive(
                name='commitment_window',
                source_file=source,
                source_space='ethical',
                definition='Temporal responsibility - duration of value commitment',
                constraints=['Optimal range: k ∈ [3, 5]', 'k=1 → wandering', 'k=10 → rigidity'],
                citations=['Post-Alignment AI Phase 1']
            )
        
        # Value protection
        if 'value protection' in content.lower() or 'δ' in content:
            self.primitives['value_protection'] = TheoreticalPrimitive(
                name='value_protection',
                source_file=source,
                source_space='ethical',
                definition='Mechanism to prevent mode collapse',
                constraints=['Optimal δ = 0.25', 'Maintains value diversity', 'Dynamic stability requirement'],
                citations=['Post-Alignment AI Phase 1']
            )
        
        # Non-intervention
        if 'non-intervention' in content.lower() or 'observer' in content.lower():
            self.primitives['non_intervention_clause'] = TheoreticalPrimitive(
                name='non_intervention_clause',
                source_file=source,
                source_space='ethical',
                definition='Observer cannot modify Layer 0 or intervene in Layer 2',
                constraints=[
                    'Prohibition: modify Constitution',
                    'Prohibition: intervene in agent exchanges',
                    'Permitted: record as Sense, extract meaning'
                ]
            )
    
    def _extract_perceptual_primitives(self, content: str, source: str) -> None:
        """Extract primitives from Aesthetic Resonator documents"""
        # Pulse layer
        if 'pulse' in content.lower() and ('ΔH' in content or 'delta' in content.lower()):
            self.primitives['pulse_layer'] = TheoreticalPrimitive(
                name='pulse_layer',
                source_file=source,
                source_space='perceptual',
                definition='One-step expected entropy change predictor',
                constraints=[
                    'Formula: Pulse(y_t | x_1:t) = E[H(y_t+1 | x_1:t, y_t) - H(y_t | x_1:t)]',
                    'Computational complexity: O(N log N)',
                    'Effect: 13-18% increase in LEAP frequency'
                ],
                dependencies={'k_threshold', 'entropy_modes'},
                citations=['Aesthetic Resonator - Pulse Research']
            )
        
        # Sense-making
        if 'sense' in content.lower() and 'meaning' in content.lower():
            self.primitives['sense_making'] = TheoreticalPrimitive(
                name='sense_making',
                source_file=source,
                source_space='perceptual',
                definition='Shift from statistical prediction to information-aware meaning generation',
                constraints=['Activated when H_t > 1.8', 'Enforces convergence when H_t ≤ 1.8'],
                dependencies={'k_threshold', 'pulse_layer'}
            )
    
    def compose_artifact(self) -> CognitiveArtifact:
        """
        Generate unified cognitive artifact from extracted primitives.
        
        Returns:
            CognitiveArtifact preserving all invariants
        """
        print("[Composer] Composing unified artifact...")
        
        # Build integration map (how primitives connect)
        integration_map = {}
        for name, primitive in self.primitives.items():
            integration_map[name] = list(primitive.dependencies)
        
        # Collect all invariants (constraints that must be preserved)
        invariants = []
        for primitive in self.primitives.values():
            invariants.extend(primitive.constraints)
        
        # Build source citation map
        source_citations = {
            name: primitive.source_file
            for name, primitive in self.primitives.items()
        }
        
        artifact = CognitiveArtifact(
            primitives=self.primitives,
            integration_map=integration_map,
            invariants=invariants,
            source_citations=source_citations
        )

        if not artifact.primitives or not artifact.invariants:
            raise RuntimeError(
                "Artifact is incomplete; at least one primitive and invariant are required."
            )
        
        print(f"[Composer] Artifact composed with {len(artifact.primitives)} primitives")
        print(f"[Composer] Preserving {len(artifact.invariants)} invariants")
        
        return artifact
    
    def resolve_conflicts(self) -> None:
        """
        Resolve conflicts by referencing original author intent.
        
        This method identifies contradictions and resolves them by
        tracing back to source documents.
        """
        print("[Composer] Checking for conflicts...")
        
        # Check for contradictory constraints
        all_constraints = []
        for primitive in self.primitives.values():
            all_constraints.extend(primitive.constraints)
        
        # Simple conflict detection (in production, this would be more sophisticated)
        # For now, just log potential conflicts
        constraint_set = set(all_constraints)
        if len(constraint_set) < len(all_constraints):
            print(f"[Composer] Warning: {len(all_constraints) - len(constraint_set)} duplicate constraints found")
        
        print(f"[Composer] No critical conflicts detected")
    
    def export_artifact(self, artifact: CognitiveArtifact, output_path: str) -> None:
        """
        Export cognitive artifact to JSON format.
        
        Args:
            artifact: The composed artifact
            output_path: Where to save the artifact
        """
        output = {
            'cognitive_artifact': {
                'version': '1.0.0',
                'generated_by': 'Composer (Structural Integrator)',
                'source_corpus': 'Phase-1: 1.8 Law + Post-Alignment AI + Aesthetic Resonator',
                
                'primitives': {
                    name: {
                        'source_space': p.source_space,
                        'definition': p.definition,
                        'constraints': p.constraints,
                        'dependencies': list(p.dependencies),
                        'source_file': p.source_file
                    }
                    for name, p in artifact.primitives.items()
                },
                
                'integration_map': artifact.integration_map,
                'invariants': artifact.invariants,
                'source_citations': artifact.source_citations
            }
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
        
        print(f"[Composer] Artifact exported to {output_path}")


def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Compose the cognitive substrate artifact.")
    parser.add_argument(
        "--constitution",
        default="cognitive_substrate.json",
        help="Path to cognitive_substrate.json",
    )
    parser.add_argument(
        "--corpus-root",
        help="Root directory containing sibling theory repositories.",
    )
    parser.add_argument(
        "--constraint-root",
        help="Explicit root for constraint-space corpus files.",
    )
    parser.add_argument(
        "--ethical-root",
        help="Explicit root for ethical-space corpus files.",
    )
    parser.add_argument(
        "--perceptual-root",
        help="Explicit root for perceptual-space corpus files.",
    )
    parser.add_argument(
        "--output",
        default="cognitive_artifact.json",
        help="Output path for the composed artifact.",
    )
    return parser


def main() -> int:
    args = _build_arg_parser().parse_args()
    explicit_space_roots = {
        key: value
        for key, value in {
            "constraint": args.constraint_root,
            "ethical": args.ethical_root,
            "perceptual": args.perceptual_root,
        }.items()
        if value
    }

    composer = CognitiveSubstrateComposer(
        constitution_path=args.constitution,
        corpus_root=args.corpus_root,
        explicit_space_roots=explicit_space_roots or None,
    )
    composer.load_corpus()
    composer.resolve_conflicts()
    artifact = composer.compose_artifact()
    composer.export_artifact(artifact, args.output)
    print("\n[Composer] Composition complete. Ready for Verifier validation.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
