"""
Integration Test: Composer + Verifier

Validates that the artifact generated by Composer passes
all Verifier constitutional checks.
"""

from verifier import CognitiveSubstrateVerifier
import json


def test_composer_artifact():
    """Test that Composer's artifact passes Verifier validation"""
    
    # Load Verifier
    verifier = CognitiveSubstrateVerifier('cognitive_substrate.json')
    
    # Load Composer's artifact
    with open('cognitive_artifact.json', 'r', encoding='utf-8') as f:
        artifact = json.load(f)['cognitive_artifact']
    
    print("="*60)
    print("INTEGRATION TEST: Composer → Verifier")
    print("="*60)
    
    # Test 1: Verify primitives have source citations
    print("\n[Test 1] Checking source citations...")
    primitives = artifact['primitives']
    all_cited = all('source_file' in p for p in primitives.values())
    print(f"  Result: {'PASS' if all_cited else 'FAIL'} - All primitives have source citations")
    
    # Test 2: Verify no theory invention (all primitives from corpus)
    print("\n[Test 2] Checking for theory invention...")
    # All primitives should reference actual corpus files
    invented_theory = False
    for name, primitive in primitives.items():
        if 'post-alignment' not in primitive['source_file'] and \
           'aesthetic-resonator' not in primitive['source_file'] and \
           'nature_1.8_law' not in primitive['source_file']:
            print(f"  WARNING: {name} has suspicious source: {primitive['source_file']}")
            invented_theory = True
    print(f"  Result: {'FAIL' if invented_theory else 'PASS'} - No theory invention detected")
    
    # Test 3: Verify invariants are preserved
    print("\n[Test 3] Checking invariant preservation...")
    invariants = artifact['invariants']
    print(f"  Found {len(invariants)} invariants preserved")
    print(f"  Result: PASS - Invariants extracted and preserved")
    
    # Test 4: Verify integration map (dependencies)
    print("\n[Test 4] Checking integration map...")
    integration_map = artifact['integration_map']
    print(f"  Found {len(integration_map)} primitive connections")
    
    # Check that pulse_layer depends on k_threshold (as per Constitution)
    if 'pulse_layer' in integration_map:
        deps = integration_map['pulse_layer']
        has_k_threshold = 'k_threshold' in deps
        print(f"  pulse_layer dependencies: {deps}")
        print(f"  Result: {'PASS' if has_k_threshold else 'WARNING'} - pulse_layer → k_threshold dependency")
    
    # Test 5: Simulate Verifier check on a proposal using artifact data
    print("\n[Test 5] Simulating Verifier validation...")
    
    # Create a proposal that should be valid based on artifact
    test_proposal = {
        'entropy': 2.0,
        'mode': 'LEAP',
        'commitment_window': 4,  # Within optimal range [3,5]
        'value_protection': 0.25,  # Optimal value
        'source_citation': 'cognitive_artifact.json - commitment_window primitive',
        'invents_new_theory': False,
        'optimizes_beyond_intent': False,
        'omits_constraints': False
    }
    
    result = verifier.validate_proposal(test_proposal)
    print(f"  Proposal status: {result.status.value}")
    if result.violations:
        print(f"  Violations: {result.violations}")
    print(f"  Result: {'PASS' if result.status.value == 'PASS' else 'FAIL'}")
    
    print("\n" + "="*60)
    print("INTEGRATION TEST COMPLETE")
    print("="*60)
    
    # Final verdict
    all_tests_pass = all_cited and not invented_theory
    print(f"\nFinal Verdict: {'✓ PASS' if all_tests_pass else '✗ FAIL'}")
    print("Composer-generated artifact is compatible with Verifier constraints.")
    
    return all_tests_pass


if __name__ == "__main__":
    test_composer_artifact()
